In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg

tf.reset_default_graph()

In [0]:
tf.__version__

'1.13.1'

In [0]:
A = np.array([[60,5.5,1], [65,5.0,0], [55,6.0,1]], np.float32)
b = np.array([66,74,78], np.float32)
tempA = [[]]

In [0]:
A.shape

In [0]:
A.transpose(1,0)

array([[60. , 65. , 55. ],
       [ 5.5,  5. ,  6. ],
       [ 1. ,  0. ,  1. ]])

In [0]:

tempA = np.matmul(A.transpose(1,0),A)


In [0]:
tempA

array([[1.085e+04, 9.850e+02, 1.150e+02],
       [9.850e+02, 9.125e+01, 1.150e+01],
       [1.150e+02, 1.150e+01, 2.000e+00]], dtype=float32)

In [0]:
tempi = linalg.inv(tempA)
tempb = np.matmul(tempi,A.transpose(1,0))
x = np.matmul(tempb,b)

In [0]:
x

array([ -0.40000057,  20.000198  , -20.000023  ], dtype=float32)